@jwt = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1MTc5MDJ9.zu-gk_NcXY-8FPMLvOwpRGQuSGxGqEf69vy13hh0tu0"
@localhost = http://localhost:3000/


### Users create (signup)
  POST {{localhost}}/users
  Content-Type: application/json

  {
    "name": "Alice Gantman",
    "email": "Alice@test.com",
    "password": "password",
    "password_confirmation": "password"
  }

### USERS SHOW
GET http://localhost:3000/users/1
Content-Type: application/json

### USER UPDATE
PATCH http://localhost:3000/users/1
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "user_id": 1,
  "name": "Ray",
  "email": "ray@gmail.com",
  "password": "",
  "password_confirmation": "",
  "phone_number": "",
  "image_url": ""
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

  {
    "email": "shanewilliams@gmail.com",
    "password": "password"
  }




### PATIENT SHOW

GET http://localhost:3000/patients/2
Content-Type: application/json


### DRUG CREATE

POST http://localhost:3000/drugs
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Trazadone",
  "frequency": "Every 4 hours",
  "patient_id": 2
}